In [1]:
import numpy as np

In [2]:
import random

Q5. Create a NumPy array of strings ['python', 'numpy, 'pandas). Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [6]:
srt = ["python", "numpy", "pandas"]
arr = np.array(srt)
arr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [21]:
array1 = np.char.upper(arr)
array1

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [22]:
array2 = np.char.lower(arr)
array2

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [26]:
array3 = np.char.swapcase(arr)
array3

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [27]:
array3 = np.char.title(arr)
array3

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [30]:
arr = np.array(["python", "numpy", "pandas","C","HTML"])
arr

array(['python', 'numpy', 'pandas', 'C', 'HTML'], dtype='<U6')

In [36]:
a = [[x.lower() for x in a]for a in arr]
a

[['p', 'y', 't', 'h', 'o', 'n'],
 ['n', 'u', 'm', 'p', 'y'],
 ['p', 'a', 'n', 'd', 'a', 's'],
 ['c'],
 ['h', 't', 'm', 'l']]

Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [44]:
arr1 = np.random.randint(1, 10,(3, 3))
arr2 = np.random.randint(1, 10,(3, 3))

In [45]:
arr1

array([[5, 8, 7],
       [9, 2, 3],
       [7, 3, 4]])

In [46]:
arr2

array([[4, 2, 4],
       [8, 2, 1],
       [8, 1, 8]])

In [47]:
arr1 + arr2

array([[ 9, 10, 11],
       [17,  4,  4],
       [15,  4, 12]])

In [49]:
arr1 * arr2

array([[20, 16, 28],
       [72,  4,  3],
       [56,  3, 32]])

In [50]:
arr1 / arr2

array([[1.25 , 4.   , 1.75 ],
       [1.125, 1.   , 3.   ],
       [0.875, 3.   , 0.5  ]])

Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [64]:
m=np.matrix([10,20,30,40,50])
m

matrix([[10, 20, 30, 40, 50]])

In [65]:
a = m.diagonal()
a

matrix([[10]])